umbrel & raspiblitz raspberry Pi prerequisits added
Tunnelsats/tunnelsats pull request #103
Opened 2023-04-19 19:57 UTC by TrezorHannes

added requirement for Umbrel and Raspiblitz supported only on raspberry Pi systems. 

Every other non-pi environments are subject to linux expertise of the customer, and we can't provide service level agreements in case of errors with the automated install routines.

2023-04-20 06:25 UTC, blckbx requested changes
few nits

2023-04-20 06:25 UTC, blckbx commented on README.md
> +- RaspiBlitz on raspberry Pi (LND / CLN) v1.8.0+
```suggestion
- RaspiBlitz (LND / CLN) v1.8.0+
```
RaspiBlitz should not be a problem running on x86_64 hardware since services stay the same.

2023-04-20 06:25 UTC, blckbx commented on README.md
> +- Umbrel-OS on raspberry Pi (CLN not yet recommended or be tech-savvy)
```suggestion
- Umbrel-OS on Raspberry Pi (LND) 0.5+ recommended
- Umbrel-OS on Raspberry Pi (CLN not yet recommended or be tech-savvy)
```

2023-04-21 20:40 UTC, TrezorHannes reviewed
LGTM

2023-04-21 20:44 UTC, TrezorHannes reviewed
Incorporating changes

2023-04-22 11:03 UTC, blckbx approved these changes
✅

2023-05-02 20:35 UTC, merged