adding lit integrated mode for baremetal setup
Tunnelsats/tunnelsats pull request #134
Opened 2024-07-15 21:33 UTC by TrezorHannes

Adding support for users running LND integrated in LIT.

- Still need to testrun in my environment, but would appreciate an early review
- Need validating how integrated LND in LIT is built in Raspiblitz and Umbrel. For now, I left those integrations unchanged

Thanks

2024-08-02 16:13 UTC, blckbx approved these changes
LGTM, only one clarification to consider

2024-08-02 16:13 UTC, blckbx commented on scripts/setupv2.sh
> +    echo "    3) LIT"
```suggestion
    echo "    3) LIT (integrated mode)"
```

shall we make it clear that this requires LiT running in "integrated mode"?

2024-08-03 07:00 UTC, blckbx submitted a review, later dismissed

2024-08-03 08:19 UTC, TrezorHannes commented on scripts/setupv2.sh
> +minor=1
@blckbx I think we agreed that this is a patch only, do we have consensus on this?

2024-08-03 08:19 UTC, TrezorHannes commented on scripts/setupv2.sh
> -  if [ $isUmbrel -eq 1 ]; then
My merge discarded this line but I think it needs to be in, would you mind reviewing and let me know @blckbx

2024-08-03 08:33 UTC, blckbx requested changes

2024-08-03 08:33 UTC, blckbx commented on scripts/setupv2.sh
> +      ;;
`$litpossible` check seems redundant to me. it's done when options are being displayed. I think we can `exit 0` here without further checks.

2024-08-03 08:33 UTC, blckbx commented on scripts/setupv2.sh
> -  if [ $isUmbrel -eq 1 ]; then
IF clause is required to distinguish between outputs

2024-08-03 08:43 UTC, TrezorHannes commented on scripts/setupv2.sh
> -  if [ $isUmbrel -eq 1 ]; then
Ack I'll get this back in

2024-08-03 08:52 UTC, TrezorHannes commented on scripts/setupv2.sh
> +      ;;
Agreed

2024-08-03 09:02 UTC, blckbx approved these changes

2024-08-03 09:58 UTC, merged